/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckButton: typeof import('./components/CheckButton.vue')['default']
    ParamsEditor: typeof import('./components/ParamsEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidatorInput: typeof import('./components/ValidatorInput.vue')['default']
  }
}
