/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DingFlow: typeof import('./components/entry/DingFlow.vue')['default']
    EventNode: typeof import('./components/nodes/EventNode.vue')['default']
    ExpressionNode: typeof import('./components/nodes/ExpressionNode.vue')['default']
    GatewayNode: typeof import('./components/nodes/GatewayNode.vue')['default']
    NodeBehavior: typeof import('./components/base/NodeBehavior.vue')['default']
    NodeWrapper: typeof import('./components/base/NodeWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceNode: typeof import('./components/nodes/ServiceNode.vue')['default']
    SubprocessNode: typeof import('./components/nodes/SubprocessNode.vue')['default']
    TaskNode: typeof import('./components/nodes/TaskNode.vue')['default']
    TippyPopover: typeof import('./components/base/TippyPopover.vue')['default']
  }
}
